name: docs-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: deps
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: docs
        run: make doc

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html
          publish_branch: gh-pages
          force_orphan: true
